// Alien abduction jokes shown during each phase of a download. Same tone as
// the original Electron app (v2.7.0) — kept verbatim, then extended with new
// ones per phase so returning users still see fresh lines.

export const J_DL = [
  "Aligning the tractor beam with your bandwidth...",
  "The file is only being mildly abducted. Stay calm.",
  "Scanning for intelligent packets... none found yet.",
  "Negotiating with the mothership over download speed.",
  "No cows were uploaded during this transfer. Probably.",
  "Converting your panic into progress bars...",
  "Beaming bytes straight into your cargo bay.",
  "The Greys say your Wi-Fi is... barely acceptable.",
  "Crop circle decryption at 47%... hold steady.",
  "Running anti-gravity defrag on your packets...",
  "Bribing the galactic firewall... one moment.",
  "Warp drive engaged. Your file is in hyperspace.",
  "The mothership wants to know if you have snacks.",
  "Routing traffic through the Andromeda bypass...",
  "Your file has passed the alien vibe check.",
  "Earthling bandwidth detected. Compensating...",
  "Filing intergalactic transfer paperwork...",
  "Abducting your file... it's not resisting much.",
  "The probe results are in: your connection is mid.",
  "Hold still. This won't hurt. The file, I mean.",
  "Performing unauthorized experiments on your data...",
  "Your ISP has been placed under galactic investigation.",
  "Probing the server... it's surprisingly cooperative.",
  "We've seen faster connections on Mars. Just saying.",
  "Recalibrating the anal— I mean, analysis beam.",
  "Don't look directly at the progress bar. Trust us.",
  "Your file is being gently interrogated in the cargo hold.",
  "Adjusting tinfoil frequencies for optimal transfer...",
  "The council of Zorp has approved this download.",
  "Translating TCP/IP into ancient Zorpian...",
  "Running your file through the intergalactic TSA...",
  "Buffering... even aliens deal with this.",
  "The mothership's IT guy says try turning it off and on.",
  "Your file has been given a complimentary probing.",
  "Downloading at the speed of bureaucracy...",
  "Our tractor beam operator is on a coffee break. One sec.",
  "Encrypting with 256-bit alien technology... and vibes.",
  "Fun fact: this download is tax-deductible on Planet X.",
  "We've abducted worse. Your file is actually pretty nice.",
  "Distracting the firewall with a crop circle...",
  "The intern is manually carrying your bytes. Be patient.",
  "Uploading a decoy cow to distract authorities...",
  "Your download has been assigned a personal Grey.",
  "Rerouting through the dark side of the moon...",
  "Sprinkling your packets with alien seasoning...",
  "The Galactic Help Desk rated your ticket: low priority.",
  "Scanning file for Earth cooties... all clear.",
  "This download is brought to you by Abductions™.",
  "Playing elevator music in the tractor beam...",
  "Your file just asked if it's being kidnapped. We said no.",
  "Deploying stealth bandwidth. Your ISP suspects nothing.",
  "Area 51 called. They want their file back.",
  "Downloading... or as we call it, 'aggressive borrowing.'",
  "The saucer just passed its emissions test. Barely.",
  "Compressing spacetime to fit your file through the wormhole.",
  "Our lawyers confirm this abduction is technically legal.",
  "Your file is enjoying the in-flight entertainment.",
  "Replacing your file's memories with fake ones... wait, wrong protocol.",
  // new for v3.0 (Rust rewrite)
  "Rust borrow checker approved this transfer. No leaks, no lies.",
  "Tokio runtime spinning up the tractor beam threads...",
  "Zero-copy abduction in progress. Efficient AND legal.",
  "The mothership upgraded to async/await. Much faster now.",
  "Memory-safe abduction: no segfaults, no witnesses.",
  "Your bytes are being borrowed, not moved. We promise.",
  "Compiling the abduction beam at opt-level 'z'...",
];

export const J_IDLE = [
  "Welcome aboard, traveler. The saucer awaits.",
  "Paste a URL. We will handle the abduction.",
  "The tractor beam is warmed up and ready.",
  "Standing by for interstellar abduction.",
  "The crew is bored. Give them a URL.",
  "Mothership status: IDLE. Feed me a link.",
  "All systems nominal. Awaiting coordinates.",
  "The aliens are doing sudoku. Give them work.",
  "Fuel levels: full. Boredom levels: critical.",
  "The probe is sterilized and ready. For files. FILES.",
  "No active abductions. The crew is playing cards.",
  "Tractor beam on standby. It's getting cold up here.",
  "The mothership is double-parked. Hurry up.",
  "Awaiting orders. The Greys are getting restless.",
  "Your saucer has been idling for 3 galactic minutes.",
  "The crew voted. They want to abduct something.",
  "Orbit is stable. Snacks are running low.",
  "The intern is polishing the tractor beam. Again.",
  "Ready when you are, Earthling. No pressure. Some pressure.",
  "We didn't fly 40 light-years for you to just sit there.",
  // new
  "Rust runtime idling at zero CPU. We're just that efficient.",
  "The mothership's dashboard shows: 0 panics, 0 unwraps in prod.",
];

export const J_DONE = [
  "Cargo secured. The mothership is pleased.",
  "File abducted. No witnesses.",
  "The Greys send their regards.",
  "Well done, Earthling. The council approves.",
  "Beam-down complete. File landed safely.",
  "The saucer crew is celebrating.",
  "Abduction complete. Adding to your permanent record.",
  "File secured. Your cooperation has been noted.",
  "Another successful abduction. Put it on the fridge.",
  "The mothership gave you 5 stars. Out of 7.",
  "File delivered. The Greys are doing a little dance.",
  "Mission accomplished. Probing was kept to a minimum.",
  "Your file has been safely returned to Earth. You're welcome.",
  "Download complete. The council has awarded you one (1) crop circle.",
  "The cargo bay is full. Of your file. And pride.",
  "Abduction report filed with Galactic HR. All clear.",
  "File extracted with surgical precision. Mostly.",
  "The crew is already bragging about this one.",
  "That file didn't even see it coming. Clean grab.",
  "Transmission complete. Tin foil hats off to you.",
  // new
  "Compiled clean, ran clean, landed clean. Rust doesn't lie.",
  "Zero memory leaks detected during this abduction. As promised.",
];

export const J_ABORT = [
  "The mothership filed a formal complaint.",
  "The file escaped back into the void.",
  "Even aliens know when to quit.",
  "The Greys are disappointed but understanding.",
  "Abort confirmed. The tractor beam is sulking.",
  "The crew wanted that file. You've hurt their feelings.",
  "Abduction canceled. The file has been released into the wild.",
  "Mission scrubbed. The intern is crying.",
  "The council will hear about this... cancellation.",
  "You pulled the plug. The saucer is judging you.",
  "The file got away. It's telling all its friends.",
  "Ejection complete. The probe retracts sadly.",
  "The Greys shrugged. They've been ghosted before.",
  "Abort successful. Awkward silence in the cockpit.",
  // new
  "Task cancelled cleanly. No dangling futures left behind.",
];

export const J_ERR = [
  "Even advanced civilizations fear edge cases.",
  "Signal lost near Neptune. Classic.",
  "The server said no. Even aliens hear that.",
  "The mothership blames your ISP.",
  "Error detected. The Greys are arguing about whose fault it is.",
  "Something went wrong. We're blaming cosmic rays.",
  "The tractor beam sneezed. That's never happened before.",
  "Your file put up a fight. Respect.",
  "Connection failed. The server has a restraining order.",
  "The wormhole collapsed. Your file is in another dimension.",
  "Error 42: The meaning of life was not found in this URL.",
  "The Greys tried percussive maintenance. Didn't help.",
  "Download failed. The intern tripped over the power cable.",
  "The server ghosted us. We're not mad, just disappointed.",
  "Abduction failed. The file had a lawyer.",
  "The mothership got a BSOD. Yes, they run Windows too.",
  "Something broke. The council is forming a subcommittee.",
  "Error: file was protected by an ancient Earth firewall (Norton).",
  "The tractor beam threw a NullPointerException. In space.",
  "Failed. The file identified as unabductable.",
  // new
  "Error unwrapped a None. In Rust. Somehow. Investigating.",
  "The Result<> came back Err. The council is not happy.",
];

export const J_YOUTUBE = [
  "Ah, YouTube. The mothership's favorite Earth channel.",
  "Extracting video essence from the tube of you.",
  "The algorithm doesn't know we're here. Good.",
  "Downloading cat videos for... research purposes.",
  "YouTube's servers just felt a disturbance in the force.",
];

export type JokePhase = "dl" | "idle" | "done" | "abort" | "err" | "youtube";

const JOKE_BANKS: Record<JokePhase, string[]> = {
  dl: J_DL,
  idle: J_IDLE,
  done: J_DONE,
  abort: J_ABORT,
  err: J_ERR,
  youtube: J_YOUTUBE,
};

export function randomJoke(phase: JokePhase): string {
  const bank = JOKE_BANKS[phase];
  return bank[Math.floor(Math.random() * bank.length)];
}
